spring:
  application:
    name: plaza
  profiles:
    active: dev
  datasource:
    driver-class-name: ${plaza.datasource.driver:${plaza.sharding-sphere.driver}}
    url: ${plaza.datasource.url:${plaza.sharding-sphere.url}}
    username: ${plaza.datasource.username:}
    password: ${plaza.datasource.password:}
  data:
    redis:
      host: ${plaza.redis.host:localhost}
      port: ${plaza.redis.port:6379}
      password: ${plaza.redis.password:}
  rabbitmq:
    host: ${plaza.rabbitmq.host:localhost}
    port: ${plaza.rabbitmq.port:5672}
    username: ${plaza.rabbitmq.username:guest}
    password: ${plaza.rabbitmq.password:guest}
    virtual-host: ${plaza.rabbitmq.virtual-host:/}
    publisher-confirm-type: CORRELATED
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: MANUAL
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml

logging:
  config: ${plaza.log.config:}
  pattern:
    dateformat: ${spring.jackson.date-format}

logstash:
  host: ${plaza.log.logstash.host:}
  port: ${plaza.log.logstash.port:}
