plaza:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://192.168.15.4:5432/plaza
    username: postgres
    password: root
  redis:
    host: 192.168.15.4
    port: 6379
    password: 6aafd6b8ff62b8b3b4c7fd82c0fd29da
  rabbitmq:
    host: 192.168.15.4
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  log:
    config: classpath:logback-logstash.xml
    logstash:
      host: 192.168.15.4
      port: 5044
